source 'https://rubygems.org'

ruby '2.0.0'

gem 'dotenv'
gem 'everypolitician', '~> 0.11.0', github: 'everypolitician/everypolitician-ruby'
gem 'everypolitician-popolo', github: 'everypolitician/everypolitician-popolo'
gem 'iso_country_codes'
gem 'json'
gem 'nokogiri', '>= 1.6.7'
gem 'octokit'
gem 'pry'
gem 'puma'
gem 'rack-test'
gem 'rake'
gem 'redcarpet'
gem 'require_all'
gem 'rubocop'
gem 'sass'
gem 'sinatra', github: 'sinatra/sinatra'
gem 'yajl-ruby', require: 'yajl'
