source 'https://rubygems.org'
ruby '2.0.0'
gem 'sinatra', github: 'sinatra/sinatra'
gem 'dotenv'
gem 'json'
gem 'puma'
gem 'nokogiri'
gem 'octokit'
gem 'redcarpet'
gem 'rack-test'
gem 'sass'
gem 'pry'
gem 'rake'
gem 'iso_country_codes'
gem 'yajl-ruby', require: 'yajl'
gem 'everypolitician-popolo'
