source 'https://rubygems.org'
ruby '2.0.0'
gem 'sinatra', github: 'sinatra/sinatra'
gem 'json'
gem 'thin'
gem 'nokogiri'
gem 'redcarpet'
gem 'rack-test'
gem 'sass'
gem 'promise'
gem 'pry'
gem 'rake'
gem 'iso_country_codes'
gem 'yajl-ruby', require: 'yajl'
